### PR TITLE
Simplify chain logic

### LINKED ISSUE #51: Single call inline chain fails
```jl
julia> @chain abs(1) 
ERROR: LoadError: Can't insert a first argument into:
1.
```

I'm interactively building a chain one step at a time, so I want to initially evaluate the first step. The block version works

```jl
@chain abs(1) begin
    
end # 1
```

just not the inline version.

### PR DESCRIPTION
**Pull request by jkrumbiegel**
Fixes https://github.com/jkrumbiegel/Chain.jl/issues/51

**Breaking**: The rules for transforming chains were simplified.
Before, there was the two-arg block syntax (this was the only syntax originally):

```julia
@chain x begin
    y
    z
end
```

the inline syntax:

```julia
@chain x y z
```

and the one-arg block syntax:

```julia
@chain begin
    x
    y
    z
end
```
All of these are now a single syntax, derived from the rule that any `begin ... end` block in the inline syntax is flattened into its lines.
This means that you can also use multiple `begin ... end` blocks, and they can be in any position, which can be nice for interactive development of a chain in the REPL.

```julia
@chain x y begin
    x
    y
    z
end u v w begin
    g
    h
    i
end
```

This is only breaking if you were using a `begin ... end` block in the inline syntax at argument 3 or higher, but you also had to be using an underscore without chaining in that begin block, which is deemed quite unlikely given the intended use of the package.
All "normal" usage of the `@chain` macro should work as it did before.

As another consequence of the refactor, chains now do not error anymore for a single argument form `@chain x` but simply return `x`.

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
@pdeffebach @bkamins any objections to this? I have not seen any `@chain` use in the wild that would be affected by the "breaking-ness" of this change. On the flipside it could potentially enable a more flexible way of working in the REPL and it simplifies the implementation.

**Comment by bkamins** [comment]
I think it is OK. In summary - now begin-end block is just flattened right? (so it has no special meaning except for following Julia parsing rules). I assume the same applies to `(; ; ; )` blocks?

**Comment by jkrumbiegel** [comment]
@bkamins yes any block just decomposes into lines, and the three previous syntax options derive from that rule plus it removes some weird edge cases I had before.
And `(; ; ;)` blocks seem to parse as `Expr(:block, ` as well, so yeah those will have the same flattening behavior.

**Comment by pdeffebach** [comment]
Thanks! This will be helpful for tacking on extra things at the end for debugging.

**Pull request merged**
